VERBOSE: True

MODEL:
  SESSION: 'IR'
  INPUT: 'vis'
  TARGET: 'ir'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 16
  NUM_EPOCHS: 300
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  SEED: 3407
  WANDB: False

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  PS_W: 256
  PS_H: 256
  TRAIN_DIR: '../dataset/VIS-IR/train/' # path to training data
  VAL_DIR: '../dataset/VIS-IR/test/'     # path to validation data
  SAVE_DIR: './checkpoints/'          # path to save models and images
  ORI: False

TESTING:
  WEIGHT: './checkpoints/best.pth'
  SAVE_IMAGES: True